---

driver:
  name: docker
platforms:
  - name: 'debian12'
    image: 'antmelekhin/docker-systemd:debian-12'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
      - '/var/lib/containerd'
    cgroupns_mode: 'host'
    privileged: true
    pre_build_image: true
    groups:
      - 'debian_family'
  - name: 'alma9'
    image: 'antmelekhin/docker-systemd:almalinux-9'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
      - '/var/lib/containerd'
    cgroupns_mode: 'host'
    privileged: true
    pre_build_image: true
    groups:
      - 'rhel_family'
provisioner:
  name: ansible
  options:
    vv: true
    D: true



