---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    vector_package: 'vector'
    vector_service: 'vector.service'
    vector_config_file: '/etc/vector/vector.yaml'

  tasks:
    - name: 'Gather Installed Packages'
      ansible.builtin.package_facts:
        manager: auto
      become: true

    - name: 'Assert Vector Package'
      ansible.builtin.assert:
        that:
          - "'{{ vector_package }}' in ansible_facts.packages"

    - name: 'Gather Vector Config File Stats'
      ansible.builtin.stat:
        path: "{{ vector_config_file }}"
      become: true
      register: ch_config_file

    - name: 'Assert Vector Config File Stats'
      ansible.builtin.assert:
        that:
           - "{{ ch_config_file.stat.exists }}"

    - name: 'Gather Local Services'
      ansible.builtin.service_facts:
      become: true

    - name: 'Assert Vector Service'
      ansible.builtin.assert:
        that:
          - "vector_service in ansible_facts.services"
          - "'running' == ansible_facts.services[vector_service].state"
          - "'enabled' == ansible_facts.services[vector_service].status"
